self.addEventListener('install', event => {
  event.waitUntil(
    caches.open('BookMySpot').then(cache => {
      return cache.addAll([
        '/',
        'Admin/admin.html',
        'Admin/banovaniRacuni.html',
        'Admin/dodajNovuKategoriju.html',
        'Admin/managerRacuna.html',
        'Admin/permisijeRacuna.html',
        'Admin/pitanja.html',
        'Admin/pitanjeSaOdgovorom.html',
        'Admin/postojeciRacuni.html',
        'Admin/urediKategoriju.html',
        'Manager/manager.html',
        'Manager/myBusiness.html',
        'Manager/newService.html',
        'Manager/reservations.html',
        'Manager/reservationsHistory.html',
        'Manager/serviceAdded.html',
        'Manager/services.html',
        'MostarSmjestaj.html',
        'NoUser/index.html',
        'NoUser/BookMySpot.png',
        'README.md',
        'User/accomodationFavorites.html',
        'User/accomodationUser.html',
        'User/beautyUser.html',
        'User/editAccount.html',
        'User/historijaPrethodneUser.html',
        'User/historijaUser.html',
        'User/hotelBristolUser.html',
        'User/ratingFilterUser.html',
        'User/tersBosankaUser.html',
        'User/user.html',
        'User/userAccount.html',
        'aboutUs.html',
        'accomodation.html',
        'beautySalon.html',
        'help.html',
        'hotelBristol.html',
        'images/BookMySpot.png',
        'images/Bristol1.jpg',
        'images/Bristol2.jpg',
        'images/Bristol3.jpg',
        'images/Bristol4.jpg',
        'images/Bristol5.jpg',
        'images/Ordinacija.jpg',
        'images/TersBosanka1.jpg',
        'images/asi.jpg',
        'images/beauty.jpg',
        'images/beautySalonLivno.jpg',
        'images/bosanka1.jpg',
        'images/bosanka2.JPG',
        'images/bosanka3.JPG',
        'images/bosanka4.jpeg',
        'images/boy.png',
        'images/bristol.jpg',
        'images/businessman.png',
        'images/fizioHistorija.jpg',
        'images/frizerskiSalonSM.jpg',
        'images/hijabiWoman.png',
        'images/jpMan.png',
        'images/krechoSlika.webp',
        'images/kreco.jpeg',
        'images/man.png',
        'images/man2.png',
        'images/man3.png',
        'images/man4.png',
        'images/man5.png',
        'images/man6.png',
        'images/man7.png',
        'images/novitas.jpg',
        'images/ordinacijaHistorija.jpg',
        'images/ordination.jpg',
        'images/pasha.jpg',
        'images/restaurant.jpg',
        'images/room.jpg',
        'images/salonLjepoteMostar.jpg',
        'images/servis.jpg',
        'images/shm.jpg',
        'images/user.png',
        'images/vehicles.jpg',
        'images/woman.png',
        'images/woman2.png',
        'images/woman3.png',
        'images/woman4.png',
        'images/woman5.png',
        'manifest.json',
        'ratingFilter.html',
        'script.js',
        'scriptHotel.js',
        'settings.html',
        'styles/aboutUs.css',
        'styles/admin.css',
        'styles/help.css',
        'styles/historijaUser.css',
        'styles/home.css',
        'styles/homeUser.css',
        'styles/hotelBristol.css',
        'styles/hotelBristolUser.css',
        'styles/loginStyle.css',
        'styles/myAccount.css',
        'styles/myBusiness.css',
        'styles/reservations.css',
        'styles/services.css',
        'styles/settings.css',
        'styles/style.css',
        'styles/tersBosanka.css',
        'styles/uredjivanjeKategorije.css',
        'tersBosanka.html'
      ]).then(() => {
        console.log('All resources have been cached successfully.');
      }).catch(error => {
        console.error('Cache.addAll failed:', error);
      });
    })
  );
});
  
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(response => {
      return response || fetch(event.request);
    })
  );
});
  
